### ISSUE TITLE
[Server] Source *.rc files in /entrypoint.sh

### ISSUE THREAD

**Issue by jhermann** [JonasAlfredsson/docker-devpi#51]
Entrypoint plugins are currently not able to change the startup environment. I think it'd make sense to add a `*.rc` case and then *source* the files found instead of executing them.

**Comment by JonasAlfredsson** [comment]
Hi jhermann,

Thank you for opening this issue, but I am not entirely sure I follow why one would want to do this. 
I have modeled my entrypoint on the one from [Nginx](https://github.com/nginxinc/docker-nginx/blob/master/entrypoint/docker-entrypoint.sh), but I now see that this has also changed to sourcing ".envsh" files, so would you mind giving me a quick rundown on how you would use this over just setting `--env` via Docker run?

Also, would it be OK to basically copy the Nginx entrypoint code and use the same ".envsh" ending instead of ".rc"?
